HealthyEats/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("order/", include("func.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

func/urls.py
from django.urls import path
from . import views

app_name = 'func'

urlpatterns = [
    path("", views.menu, name="order"),
    path("add/<int:item_id>", views.addToCart, name="add"),
    path("remove/<int:cartEntryId>", views.removeFromCart, name="remove"),
    path("cart", views.cart, name="cart"),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path("", views.homepage, name="homepage"),
]

func/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    calories = models.IntegerField()
    protein = models.IntegerField()
    fat = models.IntegerField()
    carbohydrates = models.IntegerField()

    image = models.ImageField(upload_to='menu/', default=f'menu/{name}.jpg')

    def __str__(self):
        return self.name
    
class Cart(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Cart {self.id}'
    
    def total_carbs(self):
        total = 0
        for entry in self.cartentry_set.all():
            total += entry.carbohydrates()
        return total
    
    def total_protein(self):
        total = 0
        for entry in self.cartentry_set.all():
            total += entry.protein()
        return total
    
    def total_fat(self):
        total = 0
        for entry in self.cartentry_set.all():
            total += entry.fat()
        return total
    
    def total_calories(self):
        total = 0
        for entry in self.cartentry_set.all():
            total += entry.calories()
        return total
    
    def total(self):
        total = 0
        for entry in self.cartentry_set.all():
            total += entry.total()
        return total

class CartEntry(models.Model):
    item = models.OneToOneField(Item, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.quantity}x {self.item.name}'

    def total(self):
        return self.quantity * self.item.price
    
    def calories(self):
        return self.quantity * self.item.calories
    
    def protein(self):
        return self.quantity * self.item.protein
    
    def fat(self):
        return self.quantity * self.item.fat
    
    def carbohydrates(self):
        return self.quantity * self.item.carbohydrates
    
    def cost(self):
        return self.quantity * self.item.price

func/views.py
from django.shortcuts import redirect, render
from .models import Cart, CartEntry, Item

from openai import OpenAI

# Create your views here.
def menu(request):
    items = Item.objects.all()
    return render(request, 'func/menu.html', {'items': items})

def addToCart(request, item_id):
    item = Item.objects.get(pk=item_id)
    cart = Cart.objects.all().first()

    cartEntry = CartEntry.objects.filter(item=item, cart=cart).first()
    if cartEntry is None:
        cartEntry = CartEntry(item=item, cart=cart, quantity=1)
    else:
        cartEntry.quantity += 1
    cartEntry.save()

    return redirect('func:order')

def removeFromCart(request, cartEntryId):
    cartEntry = CartEntry.objects.get(pk=cartEntryId)
    cartEntry.delete()
    return redirect('func:cart')

def cart(request):
    cart = Cart.objects.all().first()
    cartEntries = CartEntry.objects.filter(cart=cart)

    token = "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"
    endpoint = "https://models.inference.ai.azure.com"
    model_name = "gpt-4o-mini"

    client = OpenAI(
        base_url=endpoint,
        api_key=token,
    )

    response = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": f"I will give you the total Calories, Carbohydrates, Proteins and Fats of the items I am planning to eat in one single meal. I want you to give me advice on whether it is too high or too low in about 1 to 2 sentences. Calories: {cart.total_calories()}, Carbohydrates: {cart.total_carbs()}, Proteins: {cart.total_protein()}, Fats: {cart.total_fat()}",
            },
        ],
        model=model_name,
    )

    print(response.choices[0].message.content)

    return render(request, 'func/cart.html', {'cartEntries': cartEntries, 'cart': cart, 'advice': response.choices[0].message.content})

main/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, "main/index.html")

func/templates/func/cart.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<style>
  body{
    margin-top:20px;
    background:#eee;
}
.ui-w-40 {
    width: 40px !important;
    height: auto;
}

.card{
    box-shadow: 0 1px 15px 1px rgba(52,40,104,.08);    
}

.ui-product-color {
    display: inline-block;
    overflow: hidden;
    margin: .144em;
    width: .875rem;
    height: .875rem;
    border-radius: 10rem;
    -webkit-box-shadow: 0 0 0 1px rgba(0,0,0,0.15) inset;
    box-shadow: 0 0 0 1px rgba(0,0,0,0.15) inset;
    vertical-align: middle;
}
</style>
<div class="container-xxl" style="padding-top: 100px;">
        <div class="card">
            <div class="card-header">
                <h2>Shopping Cart</h2>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered m-0">
                    <thead>
                      <tr>
                        <!-- Set columns width -->
                        <th class="text-center py-3 px-4" style="min-width: 400px;">Product Name &amp; Details</th>
                        <th class="text-right py-3 px-4" style="width: 100px;">Price</th>
                        <th class="text-center py-3 px-4" style="width: 120px;">Quantity</th>
                        <th class="text-right py-3 px-4" style="width: 100px;">Total</th>
                        <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>
                      </tr>
                    </thead>
                    <tbody>
                      
                      {% for item in cartEntries %}
                      <tr>
                        <td class="p-4">
                          <div class="media align-items-center">
                            <img src="{{item.item.image.url}}" class="d-block ui-w-40 ui-bordered mr-4" alt="">
                            <div class="media-body">
                              <a href="#" class="d-block text-dark">{{item.item.name}}</a>
                              <small>
                                <span class="text-dark">Calories:</span> {{ item.calories }}
                                <span class="text-dark">Protein:</span> {{ item.protein }}
                                <span class="text-dark">Fat:</span> {{ item.fat }}
                                <span class="text-dark">Carbohydrates:</span> {{ item.carbohydrates }}
                              </small>
                            </div>
                          </div>
                        </td>
                        <td class="text-right font-weight-semibold align-middle p-4">₹{{item.item.price}}</td>
                        <td class="align-middle p-4"><input type="text" class="form-control text-center" value="{{item.quantity}}" disabled></td>
                        <td class="text-right font-weight-semibold align-middle p-4">₹{{item.cost}}</td>
                        <td class="text-center align-middle px-0"><a href="{% url 'func:remove' item.id %}" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- / Shopping cart table -->

                <div style="padding-top: 10px;">
                  Total Calories: {{cart.total_calories}}<br>
                  Total Protein: {{cart.total_protein}}<br>
                  Total Fat: {{cart.total_fat}}<br>
                  Total Carbohydrates: {{cart.total_carbs}}
                </div>

                <div style="padding-top: 10px;">
                  <b>Healthy Eats Advice:</b> {{advice}}
                </div>
            
                <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
                  <div class="d-flex">
                    <div class="text-right mt-4">
                      <label class="text-muted font-weight-normal m-0">Total price</label>
                      <div class="text-large"><strong>Rs. {{cart.total}}</strong></div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
      </div>
{% endblock %}

func/templates/func/menu.html
{% extends "layout.html" %}
{% load static %}

{% block head %}
<link href="{% static 'func/order/css/style.css' %}" rel="stylesheet" />
<link href="{% static 'func/order/css/responsive.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="container-xxl py-5">
    <section class="food_section layout_padding">
        <div class="container">
            <div class="heading_container heading_center">
                <h2>
                    Our Menu
                </h2>
            </div>
            <div>
                <div class="row grid">
                    {% for item in items %}
                    <div class="col-sm-6 col-lg-4 all pizza">
                        <div class="box">
                            <div>
                                <div class="img-box">
                                    <img src="{{ item.image.url }}" alt="{{ item.name }}">
                                </div>
                                <div class="detail-box">
                                    <div style="font-size: large; font-weight: bold;">
                                        {{ item.name }}
                                    </div>
                                    <p>
                                        {{ item.description }}<br><br>
                                        <b>Calories:</b> {{item.calories}}, <b>Protein:</b> {{item.protein}}, <b>Fat:</b> {{item.fat}}, <b>Carbs:</b> {{item.carbohydrates}}
                                    </p>
                                    <div class="options">
                                        <p>
                                            <b>₹{{ item.price }}</b>
                                        </p>

                                        <a href="{% url 'func:add' item.id %}" style="font-size: x-large; color: black;">
                                            +
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <!-- end food section -->
</div>
{% endblock %}

main/templates/main/hero.html
{% load static %}

<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container my-5 py-5">
        <div class="row align-items-center g-5">
            <div class="col-lg-6 text-center text-lg-start">
                <h1 class="display-3 text-white animated slideInLeft">Enjoy Our<br>Healthy Meal</h1>
                <p class="text-white animated slideInLeft mb-4 pb-2">Healthy Eats is a cutting-edge food delivery and 
                    health management platform that combines delicious, nutritious meals with personalized insights 
                    to help users make better food choices and achieve their health goals.</p>
                <a href="{% url 'func:order' %}" class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">Order Now</a>
            </div>
            <div class="col-lg-6 text-center text-lg-end overflow-hidden">
                <img class="img-fluid" src="{% static 'main/img/hero.png' %}" alt="">
            </div>
        </div>
    </div>
</div>

main/templates/main/index.html
{% extends 'layout.html' %}
{% load static %}

{% block hero %}
{% include "main/hero.html" %}
{% endblock %}

{% block content %}
<!-- Service Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-4">
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="service-item rounded pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-user-tie text-primary mb-4"></i>
                        <h5>Master Chefs</h5>
                        <p>Food is prepared by Michelin Star chefs.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                <div class="service-item rounded pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-utensils text-primary mb-4"></i>
                        <h5>Quality Food</h5>
                        <p>No compromise on the quality and taste of the food.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                <div class="service-item rounded pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-cart-plus text-primary mb-4"></i>
                        <h5>Online Order</h5>
                        <p>Available 24/7 to order online from your place of comfort.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                <div class="service-item rounded pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-headset text-primary mb-4"></i>
                        <h5>Analytics</h5>
                        <p>Information on health impacts of the food you order</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Service End -->

<!-- Team Start -->
<div class="container-xxl pt-5 pb-3">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h5 class="section-title ff-secondary text-center text-primary fw-normal">Team Members</h5>
            <h1 class="mb-5">Our Master Chefs</h1>
        </div>
        <div class="row g-4">
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="team-item text-center rounded overflow-hidden">
                    <div class="rounded-circle overflow-hidden m-4">
                        <img class="img-fluid" src="{% static 'main/img/team-1.jpg' %}" alt="">
                    </div>
                    <h5 class="mb-0">Marco Deluca</h5>
                    <small>Chief Chef</small>
                    <div class="d-flex justify-content-center mt-3">
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                <div class="team-item text-center rounded overflow-hidden">
                    <div class="rounded-circle overflow-hidden m-4">
                        <img class="img-fluid" src="{% static 'main/img/team-2.jpg' %}" alt="">
                    </div>
                    <h5 class="mb-0">Ethan Brooks</h5>
                    <small>Assistant Chef</small>
                    <div class="d-flex justify-content-center mt-3">
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                <div class="team-item text-center rounded overflow-hidden">
                    <div class="rounded-circle overflow-hidden m-4">
                        <img class="img-fluid" src="{% static 'main/img/team-3.jpg' %}" alt="">
                    </div>
                    <h5 class="mb-0">Liam Carter</h5>
                    <small>Assistant Chef</small>
                    <div class="d-flex justify-content-center mt-3">
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">
                <div class="team-item text-center rounded overflow-hidden">
                    <div class="rounded-circle overflow-hidden m-4">
                        <img class="img-fluid" src="{% static 'main/img/team-4.jpg' %}" alt="">
                    </div>
                    <h5 class="mb-0">Gabriel Martinez</h5>
                    <small>Quality Manager</small>
                    <div class="d-flex justify-content-center mt-3">
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Team End -->


<!-- Testimonial Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="text-center">
            <h5 class="section-title ff-secondary text-center text-primary fw-normal">Testimonial</h5>
            <h1 class="mb-5">Our Clients Say!!!</h1>
        </div>
        <div class="owl-carousel testimonial-carousel">
            <div class="testimonial-item bg-transparent border rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>Healthy Eats has completely transformed the way I approach my meals. Not only are the dishes delicious, but the detailed nutritional breakdown helps me stay on track with my health goals. It’s like having a dietitian and chef in one!</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'main/img/testimonial-1.jpg' %}" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">Sarah T.</h5>
                        <small>Fitness Enthusiast</small>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-transparent border rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>As someone with dietary restrictions, finding tasty options used to be a challenge. Healthy Eats makes it so easy to customize meals while providing peace of mind with clear nutritional info. Highly recommend!</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'main/img/testimonial-2.jpg' %}" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">John M.</h5>
                        <small>Gluten-Free Advocate</small>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-transparent border rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>The health impact analysis feature is a game-changer. I love how it shows me the benefits of each meal I choose. It’s not just food delivery; it’s a smarter way to eat.</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'main/img/testimonial-3.jpg' %}" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">David L.</h5>
                        <small>Busy Professional</small>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-transparent border rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>From fresh, sustainable ingredients to the convenience of doorstep delivery, Healthy Eats has checked all the boxes for me and my family. Eating healthy has never been this simple or enjoyable!</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'main/img/testimonial-4.jpg' %}" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">Emily R.</h5>
                        <small>Family Man</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial End -->
{% endblock %}

main/templates/main/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
    <a href="" class="navbar-brand p-0">
        <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Healthy Eats</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="fa fa-bars"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto py-0 pe-4">
            <a href="{% url 'main:homepage' %}" class="nav-item nav-link active">Home</a>
        </div>
        <a href="" class="btn btn-primary py-2 px-4">Order Now</a>
    </div>
</nav>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
    <a href="" class="navbar-brand p-0">
        <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Healthy Eats</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="fa fa-bars"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto py-0 pe-4">
            <a href="{% url 'main:homepage' %}" class="nav-item nav-link active">Home</a>
            <a href="{% url 'func:cart' %}" class="nav-item nav-link active">Cart</a>
        </div>
        <a href="{% url 'func:order' %}" class="btn btn-primary py-2 px-4">Order Now</a>
    </div>
</nav>